# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x06\n\x04Null\"A\n\x06Ticket\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0cstory_points\x18\x03 \x01(\r\")\n\x0c\x43onfirmation\x12\x19\n\x11\x65xpected_dateline\x18\x01 \x01(\t2J\n\x0bTestService\x12\x16\n\x06Health\x12\x05.Null\x1a\x05.Null\x12#\n\tAddTicket\x12\x07.Ticket\x1a\r.Confirmationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NULL']._serialized_start=17
  _globals['_NULL']._serialized_end=23
  _globals['_TICKET']._serialized_start=25
  _globals['_TICKET']._serialized_end=90
  _globals['_CONFIRMATION']._serialized_start=92
  _globals['_CONFIRMATION']._serialized_end=133
  _globals['_TESTSERVICE']._serialized_start=135
  _globals['_TESTSERVICE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
