"""

Message: update model booking
Revision ID: aec44f752007
Revises: 4037f65e5dd0
Create Date: 2023-05-24 15:48:46.885261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec44f752007'
down_revision = '4037f65e5dd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('state', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'state')
    # ### end Alembic commands ###
