"""

Message: this is a new model
Revision ID: fdd317aba775
Revises: e6d9bbdce363
Create Date: 2023-05-23 16:41:14.547277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd317aba775'
down_revision = 'fde6ff22eeb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
