"""

Message: empty message
Revision ID: 8f9009b73f64
Revises: 7937b3f3a453
Create Date: 2023-05-24 16:41:29.419576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9009b73f64'
down_revision = '7937b3f3a453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_parent',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('student_id', 'parent_id')
    )
    op.add_column('student', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'grade', ['grade_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'grade_id')
    op.drop_table('student_parent')
    # ### end Alembic commands ###
