"""

Message: empty message
Revision ID: 6be32617d7e4
Revises: aec44f752007
Create Date: 2023-05-25 00:23:13.774061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6be32617d7e4'
down_revision = 'aec44f752007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tutor_ibfk_2', 'tutor', type_='foreignkey')
    op.drop_constraint('tutor_ibfk_1', 'tutor', type_='foreignkey')
    op.drop_column('tutor', 'grade_id')
    op.drop_column('tutor', 'subject_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('subject_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tutor', sa.Column('grade_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tutor_ibfk_1', 'tutor', 'grade', ['grade_id'], ['id'])
    op.create_foreign_key('tutor_ibfk_2', 'tutor', 'subject', ['subject_id'], ['id'])
    # ### end Alembic commands ###
