"""

Message: empty message
Revision ID: fde6ff22eeb9
Revises: 8f9009b73f64
Create Date: 2023-05-24 20:47:24.945978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde6ff22eeb9'
down_revision = '8f9009b73f64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('location_id', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'location_id')
    # ### end Alembic commands ###
