"""

Message: empty message
Revision ID: e6d9bbdce363
Revises: e60101862ad3
Create Date: 2023-05-22 16:37:34.916453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d9bbdce363'
down_revision = 'e60101862ad3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True, comment='code of areas'),
    sa.Column('gov_code', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('geometry', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=45), nullable=True),
    sa.Column('place_id', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('grade', sa.Column('image', sa.String(length=1024), nullable=True, comment='Link image'))
    op.add_column('subject', sa.Column('image', sa.String(length=1024), nullable=True, comment='Link image'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'image')
    op.drop_column('grade', 'image')
    op.drop_table('areas')
    # ### end Alembic commands ###
