"""

Message: empty message
Revision ID: 948df51991cb
Revises: e6d9bbdce363
Create Date: 2023-05-23 10:53:11.916966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948df51991cb'
down_revision = 'e6d9bbdce363'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verify', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verify')
    # ### end Alembic commands ###
