"""

Message: empty message
Revision ID: a88bd5a376c1
Revises: 37d6ba65e373
Create Date: 2023-06-04 20:26:41.692902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88bd5a376c1'
down_revision = '37d6ba65e373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_tutor',
    sa.Column('user_rating_id', sa.Integer(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_rating_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tutor', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor', 'rating')
    op.drop_table('rating_tutor')
    # ### end Alembic commands ###
