"""

Message: empty message
Revision ID: e102c82e4567
Revises: a88bd5a376c1
Create Date: 2023-06-04 21:15:06.574557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e102c82e4567'
down_revision = 'a88bd5a376c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('state', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
