"""

Message: empty message
Revision ID: 56483f59f7bc
Revises: 847213993564
Create Date: 2023-05-30 00:52:56.106466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56483f59f7bc'
down_revision = '847213993564'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('location', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'location')
    # ### end Alembic commands ###
