"""

Message: empty message
Revision ID: 8fa61e025bc9
Revises: 798b02b18f0a
Create Date: 2023-06-04 23:16:48.183550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa61e025bc9'
down_revision = '798b02b18f0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('introduction', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor', 'introduction')
    # ### end Alembic commands ###
