"""

Message: empty message
Revision ID: 37d6ba65e373
Revises: cba50694c52a
Create Date: 2023-06-04 11:19:12.436617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d6ba65e373'
down_revision = 'cba50694c52a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center',
    sa.Column('name', sa.String(length=256), nullable=True, comment='Name of center'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='Mô tả'),
    sa.Column('thumbnail', sa.String(length=1024), nullable=True, comment='Link image'),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=1024), nullable=True),
    sa.Column('location_id', sa.String(length=6), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('center_subject',
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('center_id', 'subject_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('center_subject')
    op.drop_table('center')
    # ### end Alembic commands ###
