"""

Message: empty message
Revision ID: 691616c71304
Revises: 8fa61e025bc9
Create Date: 2023-06-05 17:10:00.583474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691616c71304'
down_revision = '8fa61e025bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('sex', sa.Enum('male', 'female', 'other', name='sex'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor', 'sex')
    # ### end Alembic commands ###
