"""

Message: empty message
Revision ID: ac6acb75da5f
Revises: e102c82e4567
Create Date: 2023-06-04 21:15:23.766617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6acb75da5f'
down_revision = 'e102c82e4567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('state', sa.Enum('pending', 'accept', 'cancel_by_parent', 'cancel_by_tutor', name='statebooking'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'state')
    # ### end Alembic commands ###
