"""

Message: empty message
Revision ID: c5061c254544
Revises: c119578c29f5
Create Date: 2023-06-04 22:27:35.951749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5061c254544'
down_revision = 'c119578c29f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('start_date', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
