"""

Message: empty message
Revision ID: d0fcb10c32ef
Revises: 6be32617d7e4
Create Date: 2023-05-25 14:57:10.024174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0fcb10c32ef'
down_revision = '6be32617d7e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('other_parent_id', sa.Integer(), nullable=True, comment='other parent'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'other_parent_id')
    # ### end Alembic commands ###
