"""

Message: empty message
Revision ID: 472f1059a6f3
Revises: 8dbf5640f277
Create Date: 2023-06-26 15:13:38.123723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472f1059a6f3'
down_revision = '8dbf5640f277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('name', sa.String(length=256), nullable=True, comment='name of School'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='Mô tả'),
    sa.Column('image', sa.String(length=1024), nullable=True, comment='Link image'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    # ### end Alembic commands ###
