"""

Message: empty message
Revision ID: eaed0ef4fe58
Revises: 26a71962bda3
Create Date: 2023-06-19 21:18:41.783763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaed0ef4fe58'
down_revision = '26a71962bda3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.Enum('Tentative', 'Confirmed', 'Cancelled', 'Rescheduled', 'Completed', 'InProgress', 'NotStarted', name='eventstatus'), nullable=True))
    op.add_column('event', sa.Column('note', sa.String(length=256), nullable=True))
    op.add_column('otp', sa.Column('retry', sa.Integer(), nullable=True))
    op.add_column('otp', sa.Column('status', sa.Enum('active', 'verify', 'expired', name='statusotp'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp', 'status')
    op.drop_column('otp', 'retry')
    op.drop_column('event', 'note')
    op.drop_column('event', 'status')
    # ### end Alembic commands ###
