"""

Message: empty message
Revision ID: 8dbf5640f277
Revises: e2989b95d5ec
Create Date: 2023-06-20 17:34:04.491436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbf5640f277'
down_revision = 'e2989b95d5ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event', sa.Column('calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'calendar', ['calendar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'calendar_id')
    op.drop_table('calendar')
    # ### end Alembic commands ###
