"""

Message: empty message
Revision ID: e2989b95d5ec
Revises: eaed0ef4fe58
Create Date: 2023-06-19 21:38:06.569198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2989b95d5ec'
down_revision = 'eaed0ef4fe58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    alter table booking
    modify state enum ('pending', 'accept', 'cancel_by_parent', 'cancel_by_tutor', 'relay') null;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
