"""

Message: empty message
Revision ID: 81da9f5a424e
Revises: 83082492ad36
Create Date: 2023-07-03 23:06:25.380681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81da9f5a424e'
down_revision = '83082492ad36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_unique', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_unique')
    # ### end Alembic commands ###
