"""

Message: empty message
Revision ID: 8522df5a36a2
Revises: 472f1059a6f3
Create Date: 2023-06-30 17:23:25.219347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8522df5a36a2'
down_revision = '472f1059a6f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('number_of_task_complete', sa.Integer(), nullable=True),
    sa.Column('number_of_task_wrong', sa.Integer(), nullable=True),
    sa.Column('number_of_task_not_complete', sa.Integer(), nullable=True),
    sa.Column('test_mark', sa.Float(), nullable=True),
    sa.Column('learning_spirit', sa.Float(), nullable=True),
    sa.Column('learning_spirit_note', sa.String(length=256), nullable=True),
    sa.Column('learning_ability', sa.Float(), nullable=True),
    sa.Column('learning_ability_note', sa.String(length=256), nullable=True),
    sa.Column('assignments', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.drop_column('notification', 'device_token')
    op.drop_column('notification', 'channel')
    op.drop_column('notification', 'data_ref_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('data_ref_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('channel', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('notification', sa.Column('device_token', mysql.VARCHAR(length=255), nullable=True))
    op.drop_table('results')
    # ### end Alembic commands ###
