"""

Message: empty message
Revision ID: f684140e0f2a
Revises: c34a398cfb28
Create Date: 2023-07-07 17:42:47.721042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f684140e0f2a'
down_revision = 'c34a398cfb28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('color', sa.String(length=256), nullable=True, comment='color'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'color')
    # ### end Alembic commands ###
