"""

Message: empty message
Revision ID: 83082492ad36
Revises: 8522df5a36a2
Create Date: 2023-07-03 23:00:56.196873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83082492ad36'
down_revision = '8522df5a36a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone_number', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone_number', 'user', ['phone_number'], unique=False)
    # ### end Alembic commands ###
