"""

Message: empty message
Revision ID: 69cbc3863a6b
Revises: f684140e0f2a
Create Date: 2023-07-10 22:57:22.576721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cbc3863a6b'
down_revision = 'f684140e0f2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_event',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('payment_id', 'event_id')
    )
    op.create_table('payment',
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Paid', 'Unpaid', 'PaymentOrder', name='paymentstatus'), nullable=True),
    sa.Column('status_admin', sa.Enum('Process', 'Done', name='paymentstatusadmin'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('payment_event')
    # ### end Alembic commands ###
