"""

Message: empty message
Revision ID: 9b2ecd57f5a4
Revises: cfca49f41f82
Create Date: 2023-07-16 10:58:11.342992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2ecd57f5a4'
down_revision = 'cfca49f41f82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.execute("""
    alter table user modify role enum('tutor', 'parent', 'student', 'admin') null;
    """)


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
