"""

Message: empty message
Revision ID: 42c64b82b166
Revises: 9b2ecd57f5a4
Create Date: 2023-07-16 22:36:51.999733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c64b82b166'
down_revision = '9b2ecd57f5a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    alter table notification
    modify type enum ('payment', 'booking', 'result') null;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
