"""

Message: empty message
Revision ID: 4ceea3a8f35c
Revises: 5d5e1cf17985
Create Date: 2023-07-21 23:03:57.396396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ceea3a8f35c'
down_revision = '5d5e1cf17985'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('device_token', table_name='device')
    op.create_unique_constraint('user_id_and_device_token', 'device', ['user_id', 'device_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_id_and_device_token', 'device', type_='unique')
    op.create_index('device_token', 'device', ['device_token'], unique=False)
    # ### end Alembic commands ###
