"""

Message: empty message
Revision ID: cfca49f41f82
Revises: 5941da9458eb
Create Date: 2023-07-15 23:49:10.661053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfca49f41f82'
down_revision = '5941da9458eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('image', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'image')
    # ### end Alembic commands ###
