"""

Message: empty message
Revision ID: 385aae017d38
Revises: ee0ff1ab8158
Create Date: 2023-07-27 17:14:51.113947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385aae017d38'
down_revision = 'ee0ff1ab8158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('location_id', sa.String(length=6), nullable=True))
    op.add_column('tutor', sa.Column('location', sa.String(length=1024), nullable=True))
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    op.drop_column('tutor', 'location')
    op.drop_column('tutor', 'location_id')
    # ### end Alembic commands ###
