"""

Message: empty message
Revision ID: 2b46a4db9522
Revises: 38e7014badb4
Create Date: 2023-07-25 21:42:47.996135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b46a4db9522'
down_revision = '38e7014badb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    alter table notification
    alter column seen set default 0;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
