"""

Message: empty message
Revision ID: ee0ff1ab8158
Revises: 2b46a4db9522
Create Date: 2023-07-26 00:08:50.594655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0ff1ab8158'
down_revision = '2b46a4db9522'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    alter table notification
    modify type enum ('payment', 'booking', 'result', 'start_event') null;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
