"""

Message: empty message
Revision ID: 0ebdbec89cdf
Revises: 
Create Date: 2023-08-25 16:07:50.631139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebdbec89cdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('full_name', sa.String(length=256), nullable=True, comment='Full Name User'),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.Column('salt', sa.String(length=256), nullable=True, comment='Salt for hash password'),
    sa.Column('role', sa.String(length=256), nullable=True),
    sa.Column('verify', sa.Boolean(), nullable=True),
    sa.Column('device_code', sa.String(length=256), nullable=True),
    sa.Column('phone_unique', sa.String(length=30), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('active', 'delete', name='userstatus'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
