"""

Message: empty message
Revision ID: bdd1af6e2274
Revises: 0ebdbec89cdf
Create Date: 2023-08-25 16:12:31.333737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdd1af6e2274'
down_revision = '0ebdbec89cdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone_unique', table_name='user')
    op.drop_column('user', 'phone_unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_unique', mysql.VARCHAR(length=30), nullable=True))
    op.create_index('phone_unique', 'user', ['phone_unique'], unique=False)
    # ### end Alembic commands ###
